export {Card} from './cards/card.jsx';
export {Home} from './home/Home.jsx';
export {Vitals} from './vitals/Vitals.jsx';
export {Display} from './display/Display.jsx';
export {Reminders} from './reminders/Reminders.jsx';
export {Symptoms} from './symptoms/Symptoms.jsx';
export {StepCount} from './stepCount/StepCount.jsx';
export {NewReminder} from './reminders/newReminder/NewReminder.jsx'
export {Meds,VitalDetail,SymptomDetail} from './symptoms/details/Details.jsx';
export {Settings} from './settingsView/Setting.jsx';
export {Resources} from './resources/Resources.jsx';
export {Notes} from './notes/notes.jsx'